DEMO_QUESTIONS = {
    "NEET": {
        "Physics": [
            {"id": "neet_phy_1", "question": "A particle moves with constant acceleration. If it travels 24 m in first 4 seconds and 64 m in next 4 seconds, what is its acceleration?", "options": ["2.5 m/s²", "5 m/s²", "7.5 m/s²", "10 m/s²"], "correctAnswer": 0, "explanation": "Using kinematic equations: a = 2.5 m/s²"},
            {"id": "neet_phy_2", "question": "The dimensional formula for angular momentum is:", "options": ["[ML²T⁻¹]", "[MLT⁻¹]", "[ML²T⁻²]", "[MLT⁻²]"], "correctAnswer": 0, "explanation": "Angular momentum L = Iω, therefore L = [ML²T⁻¹]"},
            {"id": "neet_phy_3", "question": "A body of mass 2 kg is moving with velocity 10 m/s. The kinetic energy of the body is:", "options": ["50 J", "100 J", "200 J", "400 J"], "correctAnswer": 1, "explanation": "Kinetic Energy = (1/2)mv² = 100 J"},
            {"id": "neet_phy_4", "question": "The escape velocity from Earth is approximately:", "options": ["7.9 km/s", "11.2 km/s", "15.0 km/s", "20.0 km/s"], "correctAnswer": 1, "explanation": "Escape velocity from Earth is 11.2 km/s"},
            {"id": "neet_phy_5", "question": "Which of the following is a scalar quantity?", "options": ["Force", "Velocity", "Work", "Acceleration"], "correctAnswer": 2, "explanation": "Work is a scalar quantity"},
            {"id": "neet_phy_6", "question": "The SI unit of electric charge is:", "options": ["Ampere", "Coulomb", "Volt", "Ohm"], "correctAnswer": 1, "explanation": "The SI unit of electric charge is Coulomb"},
            {"id": "neet_phy_7", "question": "The speed of light in vacuum is:", "options": ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10⁷ m/s", "3 × 10⁹ m/s"], "correctAnswer": 0, "explanation": "Speed of light is 3 × 10⁸ m/s"},
            {"id": "neet_phy_8", "question": "Ohm's law states that:", "options": ["V = IR", "I = VR", "R = VI", "V = I/R"], "correctAnswer": 0, "explanation": "Ohm's law: V = IR"},
            {"id": "neet_phy_9", "question": "The unit of power is:", "options": ["Joule", "Watt", "Newton", "Pascal"], "correctAnswer": 1, "explanation": "The SI unit of power is Watt"},
            {"id": "neet_phy_10", "question": "Newton's second law of motion is:", "options": ["F = ma", "F = m/a", "F = a/m", "F = m + a"], "correctAnswer": 0, "explanation": "Newton's second law: F = ma"},
            {"id": "neet_phy_11", "question": "The centripetal force is directed:", "options": ["Tangent to circle", "Away from center", "Towards center", "Perpendicular"], "correctAnswer": 2, "explanation": "Centripetal force is towards the center"},
            {"id": "neet_phy_12", "question": "The refractive index of water is approximately:", "options": ["1.0", "1.33", "1.5", "2.4"], "correctAnswer": 1, "explanation": "Refractive index of water is 1.33"},
            {"id": "neet_phy_13", "question": "The acceleration due to gravity on Earth is:", "options": ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "11.8 m/s²"], "correctAnswer": 1, "explanation": "g = 9.8 m/s²"},
            {"id": "neet_phy_14", "question": "Which law explains rocket propulsion?", "options": ["Newton's 1st", "Newton's 2nd", "Newton's 3rd", "Gravitation"], "correctAnswer": 2, "explanation": "Newton's third law"},
            {"id": "neet_phy_15", "question": "The frequency of visible light is in range:", "options": ["10⁹-10¹² Hz", "10¹²-10¹⁵ Hz", "10¹⁴-10¹⁵ Hz", "10¹⁵-10¹⁸ Hz"], "correctAnswer": 2, "explanation": "Visible light: 10¹⁴-10¹⁵ Hz"}
        ],
        "Chemistry": [
            {"id": "neet_chem_1", "question": "The atomic number of carbon is:", "options": ["4", "6", "8", "12"], "correctAnswer": 1, "explanation": "Carbon has atomic number 6"},
            {"id": "neet_chem_2", "question": "Which is a noble gas?", "options": ["Oxygen", "Nitrogen", "Helium", "Hydrogen"], "correctAnswer": 2, "explanation": "Helium is a noble gas"},
            {"id": "neet_chem_3", "question": "The pH of pure water at 25°C is:", "options": ["0", "7", "14", "1"], "correctAnswer": 1, "explanation": "Pure water pH = 7"},
            {"id": "neet_chem_4", "question": "The valency of oxygen is:", "options": ["1", "2", "3", "4"], "correctAnswer": 1, "explanation": "Oxygen valency = 2"},
            {"id": "neet_chem_5", "question": "Molecular formula of glucose is:", "options": ["C₆H₁₂O₆", "C₆H₁₀O₆", "C₅H₁₂O₆", "C₆H₁₂O₅"], "correctAnswer": 0, "explanation": "Glucose: C₆H₁₂O₆"},
            {"id": "neet_chem_6", "question": "Most abundant element in Earth's crust:", "options": ["Iron", "Silicon", "Oxygen", "Carbon"], "correctAnswer": 2, "explanation": "Oxygen is most abundant"},
            {"id": "neet_chem_7", "question": "Solid to gas conversion is called:", "options": ["Melting", "Sublimation", "Evaporation", "Condensation"], "correctAnswer": 1, "explanation": "Sublimation"},
            {"id": "neet_chem_8", "question": "Hardest natural substance:", "options": ["Gold", "Iron", "Diamond", "Platinum"], "correctAnswer": 2, "explanation": "Diamond is hardest"},
            {"id": "neet_chem_9", "question": "Avogadro's number is:", "options": ["6.022×10²³", "6.022×10²²", "6.022×10²⁴", "6.022×10²¹"], "correctAnswer": 0, "explanation": "6.022 × 10²³"},
            {"id": "neet_chem_10", "question": "Symbol for sodium:", "options": ["S", "So", "Na", "Sd"], "correctAnswer": 2, "explanation": "Sodium: Na"},
            {"id": "neet_chem_11", "question": "An acid tastes:", "options": ["Sweet", "Sour", "Bitter", "Salty"], "correctAnswer": 1, "explanation": "Acids taste sour"},
            {"id": "neet_chem_12", "question": "Electronic configuration of helium:", "options": ["1s¹", "1s²", "2s²", "1s²2s²"], "correctAnswer": 1, "explanation": "Helium: 1s²"},
            {"id": "neet_chem_13", "question": "Most reactive metal:", "options": ["Iron", "Sodium", "Gold", "Francium"], "correctAnswer": 3, "explanation": "Francium is most reactive"},
            {"id": "neet_chem_14", "question": "Catalyst in Haber's process:", "options": ["Platinum", "Iron", "Nickel", "Copper"], "correctAnswer": 1, "explanation": "Iron catalyst"},
            {"id": "neet_chem_15", "question": "Water has maximum density at:", "options": ["0°C", "4°C", "25°C", "100°C"], "correctAnswer": 1, "explanation": "Maximum density at 4°C"}
        ],
        "Biology": [
            {"id": "neet_bio_1", "question": "Powerhouse of the cell:", "options": ["Nucleus", "Mitochondria", "Ribosome", "Golgi body"], "correctAnswer": 1, "explanation": "Mitochondria produces ATP"},
            {"id": "neet_bio_2", "question": "DNA stands for:", "options": ["Deoxyribonucleic Acid", "Diribonucleic Acid", "Deoxyribose Acid", "Diribose Nucleic Acid"], "correctAnswer": 0, "explanation": "Deoxyribonucleic Acid"},
            {"id": "neet_bio_3", "question": "Largest organ in human body:", "options": ["Liver", "Brain", "Skin", "Heart"], "correctAnswer": 2, "explanation": "Skin is largest organ"},
            {"id": "neet_bio_4", "question": "Photosynthesis occurs in:", "options": ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"], "correctAnswer": 1, "explanation": "Chloroplast"},
            {"id": "neet_bio_5", "question": "Normal human body temperature:", "options": ["35°C", "36°C", "37°C", "38°C"], "correctAnswer": 2, "explanation": "37°C"},
            {"id": "neet_bio_6", "question": "Chromosomes in human cells:", "options": ["23", "46", "92", "24"], "correctAnswer": 1, "explanation": "46 chromosomes"},
            {"id": "neet_bio_7", "question": "Functional unit of kidney:", "options": ["Neuron", "Nephron", "Axon", "Dendrite"], "correctAnswer": 1, "explanation": "Nephron"},
            {"id": "neet_bio_8", "question": "Universal donor blood group:", "options": ["A", "B", "AB", "O"], "correctAnswer": 3, "explanation": "O is universal donor"},
            {"id": "neet_bio_9", "question": "Study of plants:", "options": ["Zoology", "Botany", "Ecology", "Mycology"], "correctAnswer": 1, "explanation": "Botany"},
            {"id": "neet_bio_10", "question": "Insulin produced by:", "options": ["Liver", "Pancreas", "Kidney", "Heart"], "correctAnswer": 1, "explanation": "Pancreas"},
            {"id": "neet_bio_11", "question": "Longest bone in human body:", "options": ["Femur", "Tibia", "Humerus", "Radius"], "correctAnswer": 0, "explanation": "Femur"},
            {"id": "neet_bio_12", "question": "Brain protected by:", "options": ["Ribs", "Skull", "Spine", "Sternum"], "correctAnswer": 1, "explanation": "Skull"},
            {"id": "neet_bio_13", "question": "Father of genetics:", "options": ["Darwin", "Mendel", "Pasteur", "Hooke"], "correctAnswer": 1, "explanation": "Gregor Mendel"},
            {"id": "neet_bio_14", "question": "Red blood cells called:", "options": ["Leukocytes", "Erythrocytes", "Thrombocytes", "Lymphocytes"], "correctAnswer": 1, "explanation": "Erythrocytes"},
            {"id": "neet_bio_15", "question": "Vitamin for blood clotting:", "options": ["A", "C", "K", "D"], "correctAnswer": 2, "explanation": "Vitamin K"}
        ]
    },
    "JEE": {
        "Physics": [
            {"id": "jee_phy_1", "question": "Centripetal acceleration in circular motion:", "options": ["v/r", "v²/r", "vr", "v/r²"], "correctAnswer": 1, "explanation": "a = v²/r"},
            {"id": "jee_phy_2", "question": "SI unit of magnetic flux:", "options": ["Tesla", "Weber", "Henry", "Gauss"], "correctAnswer": 1, "explanation": "Weber"},
            {"id": "jee_phy_3", "question": "Young's modulus is ratio of:", "options": ["Stress/strain", "Strain/stress", "Force/area", "Length/area"], "correctAnswer": 0, "explanation": "Stress to strain"},
            {"id": "jee_phy_4", "question": "Capacitance of parallel plate:", "options": ["ε₀A/d", "ε₀d/A", "A/ε₀d", "d/ε₀A"], "correctAnswer": 0, "explanation": "C = ε₀A/d"},
            {"id": "jee_phy_5", "question": "Work by conservative force in closed path:", "options": ["Maximum", "Minimum", "Zero", "Infinite"], "correctAnswer": 2, "explanation": "Zero"},
            {"id": "jee_phy_6", "question": "Interference based on:", "options": ["Particle", "Wave", "Quantum", "Dual"], "correctAnswer": 1, "explanation": "Wave nature"},
            {"id": "jee_phy_7", "question": "Energy of photon:", "options": ["hf", "h/f", "f/h", "hf²"], "correctAnswer": 0, "explanation": "E = hf"},
            {"id": "jee_phy_8", "question": "Coefficient of restitution for elastic collision:", "options": ["0", "0.5", "1", "Infinity"], "correctAnswer": 2, "explanation": "e = 1"},
            {"id": "jee_phy_9", "question": "Lenz's law is consequence of:", "options": ["Charge", "Momentum", "Energy", "Mass"], "correctAnswer": 2, "explanation": "Conservation of energy"},
            {"id": "jee_phy_10", "question": "Time period of pendulum independent of:", "options": ["Length", "Mass", "Gravity", "Amplitude"], "correctAnswer": 1, "explanation": "Independent of mass"},
            {"id": "jee_phy_11", "question": "Torque on coil maximum when:", "options": ["0°", "45°", "90°", "180°"], "correctAnswer": 2, "explanation": "θ = 90°"},
            {"id": "jee_phy_12", "question": "Dimensional formula of Planck's constant:", "options": ["[ML²T⁻¹]", "[ML²T⁻²]", "[MLT⁻¹]", "[ML²T⁻³]"], "correctAnswer": 0, "explanation": "[ML²T⁻¹]"},
            {"id": "jee_phy_13", "question": "RMS velocity proportional to:", "options": ["√T", "T", "√(1/T)", "1/T"], "correctAnswer": 0, "explanation": "∝ √T"},
            {"id": "jee_phy_14", "question": "Wire stretched to double length, resistance becomes:", "options": ["R/2", "R", "2R", "4R"], "correctAnswer": 3, "explanation": "4R"},
            {"id": "jee_phy_15", "question": "Radius of gyration depends on:", "options": ["Mass only", "Shape only", "Mass and shape", "Axis and mass distribution"], "correctAnswer": 3, "explanation": "Axis and distribution"}
        ],
        "Chemistry": [
            {"id": "jee_chem_1", "question": "Oxidation state of Cr in K₂Cr₂O₇:", "options": ["+2", "+4", "+6", "+7"], "correctAnswer": 2, "explanation": "+6"},
            {"id": "jee_chem_2", "question": "Hybridization of carbon in methane:", "options": ["sp", "sp²", "sp³", "sp³d"], "correctAnswer": 2, "explanation": "sp³"},
            {"id": "jee_chem_3", "question": "Conjugate base of H₂SO₄:", "options": ["SO₄²⁻", "HSO₄⁻", "H₃SO₄⁺", "H₂SO₃"], "correctAnswer": 1, "explanation": "HSO₄⁻"},
            {"id": "jee_chem_4", "question": "Shape of SF₆:", "options": ["Tetrahedral", "Octahedral", "Square planar", "Trigonal bipyramidal"], "correctAnswer": 1, "explanation": "Octahedral"},
            {"id": "jee_chem_5", "question": "Quantum number for orbital shape:", "options": ["n", "l", "m", "s"], "correctAnswer": 1, "explanation": "l (azimuthal)"},
            {"id": "jee_chem_6", "question": "Metal with highest melting point:", "options": ["Iron", "Tungsten", "Gold", "Platinum"], "correctAnswer": 1, "explanation": "Tungsten"},
            {"id": "jee_chem_7", "question": "Electrophile:", "options": ["Donates e⁻", "Accepts e⁻", "Donates H⁺", "Accepts H⁺"], "correctAnswer": 1, "explanation": "Accepts electrons"},
            {"id": "jee_chem_8", "question": "IUPAC name of CH₃-CH(CH₃)-CH₃:", "options": ["Butane", "Propane", "2-Methylpropane", "Isobutane"], "correctAnswer": 2, "explanation": "2-methylpropane"},
            {"id": "jee_chem_9", "question": "Element with maximum catenation:", "options": ["Oxygen", "Nitrogen", "Carbon", "Sulfur"], "correctAnswer": 2, "explanation": "Carbon"},
            {"id": "jee_chem_10", "question": "pH of 0.001M HCl:", "options": ["1", "2", "3", "4"], "correctAnswer": 2, "explanation": "pH = 3"},
            {"id": "jee_chem_11", "question": "Fluorine cannot show positive oxidation because:", "options": ["No d-orbitals", "Most electronegative", "Smallest halogen", "All"], "correctAnswer": 3, "explanation": "All of the above"},
            {"id": "jee_chem_12", "question": "π bonds in benzene:", "options": ["3", "6", "9", "12"], "correctAnswer": 0, "explanation": "3 π bonds"},
            {"id": "jee_chem_13", "question": "Bauxite is ore of:", "options": ["Iron", "Copper", "Aluminum", "Zinc"], "correctAnswer": 2, "explanation": "Aluminum"},
            {"id": "jee_chem_14", "question": "Entropy at absolute zero:", "options": ["Maximum", "Minimum", "Zero", "Infinity"], "correctAnswer": 2, "explanation": "Zero"},
            {"id": "jee_chem_15", "question": "Ziegler-Natta catalyst for:", "options": ["Vinyl chloride", "Ethylene", "Styrene", "Propylene"], "correctAnswer": 1, "explanation": "Ethylene"}
        ],
        "Maths": [
            {"id": "jee_math_1", "question": "Derivative of sin(x):", "options": ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"], "correctAnswer": 0, "explanation": "cos(x)"},
            {"id": "jee_math_2", "question": "∫e^x dx =", "options": ["e^x", "e^x + C", "xe^x", "e^x/x"], "correctAnswer": 1, "explanation": "e^x + C"},
            {"id": "jee_math_3", "question": "If |A|=5, |2A| for 2×2 matrix:", "options": ["5", "10", "20", "40"], "correctAnswer": 2, "explanation": "|2A| = 2²|A| = 20"},
            {"id": "jee_math_4", "question": "Sum of first n natural numbers:", "options": ["n(n-1)/2", "n(n+1)/2", "n²", "n(n+1)"], "correctAnswer": 1, "explanation": "n(n+1)/2"},
            {"id": "jee_math_5", "question": "Line through origin with slope m:", "options": ["y=mx", "y=mx+c", "x=my", "y=x/m"], "correctAnswer": 0, "explanation": "y = mx"},
            {"id": "jee_math_6", "question": "sin²θ + cos²θ =", "options": ["0", "1", "sin(2θ)", "cos(2θ)"], "correctAnswer": 1, "explanation": "1"},
            {"id": "jee_math_7", "question": "If log₁₀2=0.301, log₁₀8=", "options": ["0.602", "0.903", "2.408", "0.451"], "correctAnswer": 1, "explanation": "3×0.301 = 0.903"},
            {"id": "jee_math_8", "question": "Distance between points:", "options": ["√[(x₂-x₁)²+(y₂-y₁)²]", "(x₂-x₁)²+(y₂-y₁)²", "|x₂-x₁|+|y₂-y₁|", "√(x₂-x₁)+√(y₂-y₁)"], "correctAnswer": 0, "explanation": "Distance formula"},
            {"id": "jee_math_9", "question": "Quadratic formula:", "options": ["(-b±√(b²-4ac))/2a", "(-b±√(b²+4ac))/2a", "(b±√(b²-4ac))/2a", "None"], "correctAnswer": 0, "explanation": "Standard formula"},
            {"id": "jee_math_10", "question": "Area of circle:", "options": ["πr", "2πr", "πr²", "4πr²"], "correctAnswer": 2, "explanation": "πr²"},
            {"id": "jee_math_11", "question": "Diagonals in n-sided polygon:", "options": ["n(n-1)/2", "n(n-3)/2", "n(n-2)/2", "n(n+1)/2"], "correctAnswer": 1, "explanation": "n(n-3)/2"},
            {"id": "jee_math_12", "question": "If A⊥B, A·B=", "options": ["1", "0", "-1", "|A||B|"], "correctAnswer": 1, "explanation": "0"},
            {"id": "jee_math_13", "question": "lim(x→0) sin(x)/x =", "options": ["0", "1", "∞", "Undefined"], "correctAnswer": 1, "explanation": "1"},
            {"id": "jee_math_14", "question": "Slope perpendicular to m:", "options": ["m", "-m", "1/m", "-1/m"], "correctAnswer": 3, "explanation": "-1/m"},
            {"id": "jee_math_15", "question": "Value of i²:", "options": ["1", "-1", "i", "-i"], "correctAnswer": 1, "explanation": "-1"}
        ]
    }
}
